<a href="https://colab.research.google.com/github/DeveloperWK/learn_pytorch/blob/main/00_practice_torch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


In [2]:
# Scalar

scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector

vector = torch.tensor([8,7,4])
vector

tensor([8, 7, 4])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([3])

In [8]:
# Matrix
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[1]

tensor([3, 4])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 4, 3])

##Random tensors
#### Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then
adjust those random numbers to better represent the data.

*`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers `*

In [15]:
# Create a random tensor of (3,4)

random_tensor = torch.

SyntaxError: invalid syntax (ipython-input-15-95748507.py, line 3)