<a href="https://colab.research.google.com/github/DeveloperWK/learn_pytorch/blob/main/00_practice_torch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch


In [3]:
# Scalar

scalar = torch.tensor(7)
scalar


tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# Vector

vector = torch.tensor([8,7,4])
vector

tensor([8, 7, 4])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([3])

In [9]:
# Matrix
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
MATRIX[1]

tensor([3, 4])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 4, 3])

##Random tensors
#### Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then
adjust those random numbers to better represent the data.

*`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers `*

In [16]:
# Create a random tensor of (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6321, 0.8584, 0.3901, 0.1785],
        [0.1195, 0.9452, 0.5332, 0.4957],
        [0.7174, 0.7430, 0.4464, 0.4316]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tansor = torch.rand(size=(300,300,3)) # height,width,colour channels(R,G,B)
random_image_size_tansor.size(),random_image_size_tansor.ndim

(torch.Size([300, 300, 3]), 3)

### Zeros and ones

In [19]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of all ones
ones = torch.ones(4,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

In [24]:
one_to_ten = torch.arange(start=1,end=11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatype
**Note**: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [27]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad=False)
float_32_tensor.dtype


torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

# Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [31]:
some_tensor =  torch.rand(3,4)
some_tensor

tensor([[0.0217, 0.9011, 0.5973, 0.3860],
        [0.6978, 0.2025, 0.9017, 0.8151],
        [0.0736, 0.1481, 0.3611, 0.3912]])

In [43]:
print("Tensor Info")
print({
    "datatype":some_tensor.dtype,
    "shape":some_tensor.shape,
    "device":some_tensor.device
})


Tensor Info
{'datatype': torch.float32, 'shape': torch.Size([3, 4]), 'device': device(type='cpu')}
