<a href="https://colab.research.google.com/github/DeveloperWK/learn_pytorch/blob/main/00_practice_torch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch


In [2]:
# Scalar

scalar = torch.tensor(7)
scalar


tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector

vector = torch.tensor([8,7,4])
vector

tensor([8, 7, 4])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([3])

In [8]:
# Matrix
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[1]

tensor([3, 4])

In [12]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 4, 3])

##Random tensors
#### Why random tensors?
Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then
adjust those random numbers to better represent the data.

*`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers `*

In [17]:
# Create a random tensor of (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8157, 0.5009, 0.6692, 0.4515],
        [0.3272, 0.2955, 0.1437, 0.4906],
        [0.9482, 0.4251, 0.5496, 0.3549]])

In [18]:
random_tensor.ndim

2

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tansor = torch.rand(size=(300,300,3)) # height,width,colour channels(R,G,B)
random_image_size_tansor.size(),random_image_size_tansor.ndim

(torch.Size([300, 300, 3]), 3)

### Zeros and ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(4,5)
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32