<a href="https://colab.research.google.com/github/DeveloperWK/learn_pytorch/blob/main/01_Manipulation_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

# Manipulating Tensors (tensor operations)

Tensor opertions include:
+ Addition
+ Subtraction
+ Multiplication (element wise)
+ Division
+ Matrix multiplication


In [ ]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [ ]:
# Addition

tensor+10

tensor([11, 12, 13])

In [ ]:
# Multiplication
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Substract
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Pytorch builtIn
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix multiplication


Two main ways of performing multiplication in neural networks and deep learning:

  1. Element-wise multiplication
  2. Matrix mutliplication (dot product)

There are two main rules that performing matrix mutliplication needs to setisfy:
  1. The **inner dimensions** must match:
     * `(3,2) @ (3,2)` won't work
     * `(2,3) @ (3,2)` will work
     * `(3,2) @ (2,3)` will work
  2. The resulting matrix has the shape of the **outer dimensions**:
     * `(2,3) @ (3,2)` -> `(2,2)`
     * `(3,2) @ (2,3)` -> `(3,3)`










In [ ]:
# Element-wise mul
print(tensor,"*", tensor)
print(f"Equals: {torch.mul(tensor,tensor)}") # tensor * tensor

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix mutliplication
%%time
torch.matmul(tensor,tensor) # matmul is builtin fuction for mutliplication matrix

CPU times: user 484 µs, sys: 0 ns, total: 484 µs
Wall time: 331 µs


tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)


tensor(14)
CPU times: user 2.28 ms, sys: 15 µs, total: 2.29 ms
Wall time: 4.22 ms


# One of the most common errors in deep learning: shape errors

In [8]:
# Shape for matrix mutliplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])
tensor_A.shape

torch.Size([3, 2])

In [10]:
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [6]:
# It's Shape Error
torch.mm(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor

In [7]:
# Error Solve
tensor_B.T.mm(tensor_A) # T for Transpose

tensor([[ 89, 116],
        [ 98, 128]])

In [9]:
# The matrix mutliplication operation works when tensor_B is is transposed
print(f" Original shapes: tensor_A {tensor_A.shape} & tensor_B {tensor_B.shape} ")
print(f" New shapes: tensor_A: {tensor_A.shape}(same shape as avobe),tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.shape} <- inner dimensions must match")
print(f"Output:\n")
output = torch.mm(tensor_A,tensor_B.T)
print(output)
print(f"\n Output shape: {output.shape}")

 Original shapes: tensor_A torch.Size([3, 2]) & tensor_B torch.Size([3, 2]) 
 New shapes: tensor_A: torch.Size([3, 2])(same shape as avobe),tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimensions must match
Output:

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

 Output shape: torch.Size([3, 3])
