# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

# Create random tensor

X =  torch.rand(7,7)
X



tensor([[0.4119, 0.3183, 0.4380, 0.5380, 0.5954, 0.3771, 0.6249],
        [0.8533, 0.9382, 0.8688, 0.4119, 0.0278, 0.1077, 0.5180],
        [0.4735, 0.9628, 0.4607, 0.5819, 0.3296, 0.4064, 0.3918],
        [0.8517, 0.1069, 0.9530, 0.6851, 0.0511, 0.0078, 0.2473],
        [0.1850, 0.2767, 0.6157, 0.7298, 0.5779, 0.1561, 0.7312],
        [0.3822, 0.1370, 0.3433, 0.6026, 0.8450, 0.4577, 0.2602],
        [0.6341, 0.9445, 0.9125, 0.6582, 0.0620, 0.9873, 0.1468]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
Y = torch.rand(1,7)
Y_Transpose = torch.t(Y)

# Perform matrix multiplication
multiplication = torch.mm(X,Y_Transpose)
multiplication


tensor([[1.8162],
        [1.9474],
        [2.0665],
        [1.5565],
        [1.8409],
        [1.8431],
        [2.2154]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor = torch.rand(7,1)
tensor.size()
# Matrix multiply tensors


torch.Size([7, 1])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
if torch.cuda.is_available:
  torch.cuda.manual_seed(1234)
  print("GPU random seed set to 1234.")
else:
    print("CUDA (GPU) is not available, so GPU seed cannot be set.")
    torch.manual_seed(1234)
    print("CPU random seed set to 1234.")


GPU random seed set to 1234.



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [3]:
# Set random seed
import torch
torch.manual_seed(0)

# Check for access to GPU
device = "gpu" if torch.cuda.is_available else "cpu"
# Create two random tensors on GPU
gpu_device = torch.device("cuda")
cpu_tensor_1 = torch.rand(2,3)
cpu_tensor_2 = torch.rand(2,3)
gpu_tensor_1 = cpu_tensor_1.to(gpu_device)
gpu_tensor_2 = cpu_tensor_2.to(gpu_device)
print(gpu_tensor_1)
print(gpu_tensor_2)


tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]], device='cuda:0')
tensor([[0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
gpu_tensor_2_transpose=torch.t(gpu_tensor_2)
mul = torch.mm(gpu_tensor_1,gpu_tensor_2_transpose)
print(mul,mul.size())

tensor([[0.9722, 0.6174],
        [0.6292, 0.4455]], device='cuda:0') torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
max_value=mul.max()
# Find min
min_value=mul.min()
print(f"max_value={max_value}")
print(f"min_value={min_value}")

max_value=0.9721932411193848
min_value=0.4454618990421295


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
max_index=mul.argmax()
print(f"max_index={max_index}")
# Find arg min
min_index=mul.argmin()
print(f"min_index={min_index}")

max_index=0
min_index=3


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [15]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_A = torch.rand(1,1,1,10)

# Remove single dimensions
tensor_B=tensor_A.squeeze(0,1,2)
# Print out tensors and their shapes
print(f"tensor_A = {tensor_A}")
print(f"tensor_A_shape = {tensor_A.shape}")
print(f"tensor_B = {tensor_B}")
print(f"tensor_B_shape = {tensor_B.shape}")


tensor_A = tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor_A_shape = torch.Size([1, 1, 1, 10])
tensor_B = tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
tensor_B_shape = torch.Size([10])
